name: Build DS3617xs 7.0.1-42218

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: DS3617xs
            version: 7.0.1-42218

    steps:
      - name: 检出项目文件
        uses: actions/checkout@v3
        
      - name: 获取当前时间
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
        
      - name: 获取项目描述
        id: desc
        run: |
          wget https://raw.githubusercontent.com/Mr-jiangrj/Redpill_Build/main/README.MD -O /home/runner/desc.txt
          echo "::set-output name=description::$(cat /home/runner/desc.txt)"
        
      - name: 环境准备
        run: |
          sudo apt update
          sudo apt-get install -y curl bspatch jq git
          git clone https://github.com/jumkey/redpill-load.git /home/runner/redpill-load
          wget https://raw.githubusercontent.com/Mr-jiangrj/Redpill_Build/main/ds3617xs_user_config.json -O /home/runner/redpill-load/ds3617xs_user_config.json
          wget https://raw.githubusercontent.com/pocopico/rp-ext/main/redpill/releases/redpill-4.4.180plus-broadwell.tgz
          tar zxvf redpill-4.4.180plus-broadwell.tgz -C ./
          mv ./redpill.ko /home/runner/redpill-load/ext/rp-lkm/redpill-linux-v4.4.180+.ko
          
      - name: 添加扩展驱动
        run: |
          cd /home/runner/redpill-load 
          ./ext-manager.sh add 'https://github.com/jumkey/redpill-load/raw/develop/redpill-misc/rpext-index.json'
          ./ext-manager.sh add 'https://github.com/pocopico/redpill-load/raw/develop/redpill-acpid/rpext-index.json'
          ./ext-manager.sh add 'https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/rpext-index.json'
          
      - name: 编译引导
        run: |
          cd /home/runner/redpill-load
          sed -i 's#https://github.com/jumkey/redpill-load/raw/develop/redpill-boot-wait/rpext-index.json#https://github.com/pocopico/rp-ext/raw/main/redpill-boot-wait/rpext-index.json#g' ./bundled-exts.json
          sed -i 's#https://github.com/jumkey/redpill-load/raw/develop/redpill-virtio/rpext-index.json#https://raw.githubusercontent.com/pocopico/redpill-load/develop/redpill-virtio/rpext-index.json#g' ./bundled-exts.json
          sed -i 's/d65ee4ed5971e38f6cdab00e1548183435b53ba49a5dca7eaed6f56be939dcd2/f7e846e2a22b62613ac5e9d6e154df0213ba4ae64a6556297af627cd1e643e5c/g' ./config/DS3617xs/7.0.1-42218/config.json
          sed -i 's/28a75e0b680517d39374260eb981b8ca9ace8810b121a30b8036fa09cfcb77fc/8e0ab965c85b348dfc9dc17392b9cf0a117756f1d1bc4c0f0d19bb610350659d/g' ./config/DS3617xs/7.0.1-42218/config.json
          sed -i 's/1b2e86fbf4006f6aa40dcd674ad449feed8b0b8317a71e2bb8bb986a74e08c57/eaddd97c40a35bbcf4092417364ca4376925fb3eb322cad0cf602d4c7973d147/g' ./config/DS3617xs/7.0.1-42218/config.json
          sudo BRP_JUN_MOD=1 BRP_DEBUG=1 BRP_USER_CFG=ds3617xs_user_config.json ./build-loader.sh '${{matrix.platform}}' '${{matrix.version}}'
          
      - name: 上传引导镜像到 Github Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Redpill-load
          name: ${{matrix.version}} Build ${{steps.date.outputs.today}}
          body: ${{steps.desc.outputs.description}}
          draft: false
          prerelease: false
          files: |
            /home/runner/redpill-load/images/*.img
            
#      - name: 删除旧的 Release 项目
#        uses: dev-drprasad/delete-older-releases@v0.2.0
#        with:
#          repo: Mr-jiangrj/Redpill_Build
#          keep_latest: 1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#      - name: 上传引导镜像到 Github Actions
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{matrix.platform}} ${{matrix.version}}
#          path: /home/runner/redpill-load/images/*.img
#          if-no-files-found: error
